### ISSUE TITLE
"iri-1.4.1.2.jar" New exception type that appears to not exist in Java 9

### ISSUE THREAD

**Issue by Raganius** [iotaledger/wallet#437]
After updating to 1.4.1.2, I got the following error:
` 11/09 18:56:21.265 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.2
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
        at com.iota.iri.IRI.main(IRI.java:55)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 1 more`

The Ubuntu 16.04.3 LTS server has java version javac 9.0.1

**After downgrading java to javac 1.8.0_151 it started working ok again:**
` {
    "appName": "IRI",
    "appVersion": "1.4.1.2",
    "duration": 21,
    "jreAvailableProcessors": 4,
    "jreFreeMemory": 6089207368,
    "jreMaxMemory": 8459911168,
    "jreTotalMemory": 8459911168,
    "jreVersion": "1.8.0_151",
    "latestMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestMilestoneIndex": 243000,
    "latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestSolidSubtangleMilestoneIndex": 243000,
    "neighbors": 9,
    "packetsQueueSize": 0,
    "time": 1510273889596,
    "tips": 82,
    "transactionsToRequest": 1
}`

**Comment by patrickwieth** [comment]
Same here on Antergos
11/13 10:48:16.406 [main] INFO  com.iota.iri.IRI - Welcome to IRI 1.4.1.2
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/ValidationException
	at com.iota.iri.IRI.main(IRI.java:55)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 1 more

**Comment by TingYuLIAO** [comment]
same problem on Mac
-----------------------------------------------------------------------
java version 9.0.1
IRI 1.4.1.2

Exception in thread "main" java.lang.NoClassDefFou
ndError: javax/xml/bind/ValidationException
        at com.iota.iri.IRI.main(IRI.java:55)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more

**Comment by patrickwieth** [comment]
actually the problem is with IRI and not wallet, my solution was removing java-9 and installing java jre8-openjdk-headless  8.u144-1, reinstall IRI, then it worked

**Comment by TingYuLIAO** [comment]
@patrickwieth  thanks for your help! I solve my problem.

**Comment by akomelj** [comment]
Add `--add-modules java.xml.bind` to Java 9 command line and it will work. Java 9 is modularized and certain modules that were enabled in previous versions by default have to be enabled manually in JRE9 for IRI to work.

**Comment by Jehoel** [comment]
@akomelj Is it possible to add that command-line option when using the Iota GUI wallet to run IRI or does that fix only work if we're starting IRI from a command-line?

**Comment by akomelj** [comment]
You should be able to modify wallet sources to specify additional JVM command line parameters and build the new version using the instructions from README.md.

IRI is launched from `App.startFullNodeProcess` function in main.js. As I am not affiliated with IOTA development, I am not the right person to do this; doing it generally would require detecting the version of JVM and adding this parameter when Java 9 is detected. Adding it to Java 9 command line causes Java to abort with an error.
